# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/User/source/repos/fanmod-cmd

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/User/source/repos/fanmod-cmd

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/User/source/repos/fanmod-cmd/CMakeFiles /mnt/c/Users/User/source/repos/fanmod-cmd//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/User/source/repos/fanmod-cmd/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named LocalFANMOD

# Build rule for target.
LocalFANMOD: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LocalFANMOD
.PHONY : LocalFANMOD

# fast build rule for target.
LocalFANMOD/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LocalFANMOD.dir/build.make CMakeFiles/LocalFANMOD.dir/build
.PHONY : LocalFANMOD/fast

#=============================================================================
# Target rules for targets named getopt

# Build rule for target.
getopt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 getopt
.PHONY : getopt

# fast build rule for target.
getopt/fast:
	$(MAKE) $(MAKESILENT) -f helpers/CMakeFiles/getopt.dir/build.make helpers/CMakeFiles/getopt.dir/build
.PHONY : getopt/fast

#=============================================================================
# Target rules for targets named nauty

# Build rule for target.
nauty: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nauty
.PHONY : nauty

# fast build rule for target.
nauty/fast:
	$(MAKE) $(MAKESILENT) -f nauty/CMakeFiles/nauty.dir/build.make nauty/CMakeFiles/nauty.dir/build
.PHONY : nauty/fast

graph64.o: graph64.cpp.o
.PHONY : graph64.o

# target to build an object file
graph64.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LocalFANMOD.dir/build.make CMakeFiles/LocalFANMOD.dir/graph64.cpp.o
.PHONY : graph64.cpp.o

graph64.i: graph64.cpp.i
.PHONY : graph64.i

# target to preprocess a source file
graph64.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LocalFANMOD.dir/build.make CMakeFiles/LocalFANMOD.dir/graph64.cpp.i
.PHONY : graph64.cpp.i

graph64.s: graph64.cpp.s
.PHONY : graph64.s

# target to generate assembly for a file
graph64.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LocalFANMOD.dir/build.make CMakeFiles/LocalFANMOD.dir/graph64.cpp.s
.PHONY : graph64.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LocalFANMOD.dir/build.make CMakeFiles/LocalFANMOD.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LocalFANMOD.dir/build.make CMakeFiles/LocalFANMOD.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LocalFANMOD.dir/build.make CMakeFiles/LocalFANMOD.dir/main.cpp.s
.PHONY : main.cpp.s

maingraph.o: maingraph.cpp.o
.PHONY : maingraph.o

# target to build an object file
maingraph.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LocalFANMOD.dir/build.make CMakeFiles/LocalFANMOD.dir/maingraph.cpp.o
.PHONY : maingraph.cpp.o

maingraph.i: maingraph.cpp.i
.PHONY : maingraph.i

# target to preprocess a source file
maingraph.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LocalFANMOD.dir/build.make CMakeFiles/LocalFANMOD.dir/maingraph.cpp.i
.PHONY : maingraph.cpp.i

maingraph.s: maingraph.cpp.s
.PHONY : maingraph.s

# target to generate assembly for a file
maingraph.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LocalFANMOD.dir/build.make CMakeFiles/LocalFANMOD.dir/maingraph.cpp.s
.PHONY : maingraph.cpp.s

output.o: output.cpp.o
.PHONY : output.o

# target to build an object file
output.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LocalFANMOD.dir/build.make CMakeFiles/LocalFANMOD.dir/output.cpp.o
.PHONY : output.cpp.o

output.i: output.cpp.i
.PHONY : output.i

# target to preprocess a source file
output.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LocalFANMOD.dir/build.make CMakeFiles/LocalFANMOD.dir/output.cpp.i
.PHONY : output.cpp.i

output.s: output.cpp.s
.PHONY : output.s

# target to generate assembly for a file
output.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LocalFANMOD.dir/build.make CMakeFiles/LocalFANMOD.dir/output.cpp.s
.PHONY : output.cpp.s

random.o: random.cpp.o
.PHONY : random.o

# target to build an object file
random.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LocalFANMOD.dir/build.make CMakeFiles/LocalFANMOD.dir/random.cpp.o
.PHONY : random.cpp.o

random.i: random.cpp.i
.PHONY : random.i

# target to preprocess a source file
random.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LocalFANMOD.dir/build.make CMakeFiles/LocalFANMOD.dir/random.cpp.i
.PHONY : random.cpp.i

random.s: random.cpp.s
.PHONY : random.s

# target to generate assembly for a file
random.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LocalFANMOD.dir/build.make CMakeFiles/LocalFANMOD.dir/random.cpp.s
.PHONY : random.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... LocalFANMOD"
	@echo "... getopt"
	@echo "... nauty"
	@echo "... graph64.o"
	@echo "... graph64.i"
	@echo "... graph64.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... maingraph.o"
	@echo "... maingraph.i"
	@echo "... maingraph.s"
	@echo "... output.o"
	@echo "... output.i"
	@echo "... output.s"
	@echo "... random.o"
	@echo "... random.i"
	@echo "... random.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

